apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ciEnvironmentSlug | default "noCiEnv" }}-{{ include "helm.fullname" . }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.env.ENVIRONMENT }}
    version: {{ .Values.image.tag }}
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.annotations }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      labels:
        app: {{ .Chart.Name }}-{{ .Values.env.ENVIRONMENT }}
        version: {{ .Values.image.tag }}
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.app.livenessProbe }}
              port: http
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: {{ .Values.app.readinessProbe }}
              port: http
            initialDelaySeconds: 120
          volumeMounts:
              - name: nfs-volume
                mountPath: /mnt/files  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: nfs-volume
          nfs:
            server: {{ .Values.env.FTP_SERVER }}
            path: {{ .Values.env.FTP_PATH }}
