{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Values.image.tag }}
{{ include "helm.labels" . | nindent 4 }}
{{- toYaml ".Values.labels" . | nindent 4 }}
{{- end -}}
